/**
 * An LR(1) grammar with precedence, and assocs.
 */

%left '+' '-'
%left '*' '/'

%%

E
  : E '+' E   { $$ = ['+', $1, $2] }
  | E '*' E   { $$ = ['*', $1, $2] }
  | 'id'      { $$ = $1 }
  | '(' E ')' { $$ = $2 }
  ;
